- name: Logstash
  hosts: logproxy
  become: yes
  gather_facts: true
  vars:
    sansible_logstash_family: 7.x
    sansible_java_version: 8
    sansible_java_apt_keyserver: 'https://keyserver.ubuntu.com'
    sansible_logstash_version: 1:7.5.2-1
    sansible_logstash_plugins:
      - logstash-patterns-core
      - logstash-filter-alter
      - logstash-output-datadog_metrics
    sansible_logstash_default_config: no
  tasks:
    - import_role:
        name: sansible.logstash
    - import_role:
        name: dimagi.commcare_logstash.logstash
      tags: configure
    - sysctl:
        name: net.core.rmem_max
        value: '26214400'
        state: present
    - name: 'Accommodate poorly functioning task within sansible.users_and_groups'
      # Task 'Enable include of /etc/sudoers.d'
      # Forces the line '#includedir /etc/sudoers.d' to be included in /etc/sudoers.
      # The up-to-date syntax is @includedir, and it's in the default file that comes with Jammy
      # but since there's no simple way to get sansible *not* to add its version of this line,
      # I'm removing the more correct line so that the dir is not included twice.
      # Including the same directory twice causes annoying stderr warning output on many commands.
      lineinfile:
        path: /etc/sudoers
        regex: '^\@includedir /etc/sudoers.d'
        state: absent
  tags: logstash

- name: FileBeat
  hosts: proxy
  become: yes
  gather_facts: true
  vars:
    sansible_java_version: 8
    sansible_java_apt_keyserver: 'https://keyserver.ubuntu.com'
    filebeat_version: 7.x
  tasks:
    - import_role:
        name: dimagi.commcare_logstash.filebeat
      when: not is_monolith
  tags: filebeat
